language: java
script: mvn clean package
jdk:
  - openjdk8

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH

install: true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && mvn -Pjacoco package sonar:sonar -Dsonar.host.url=https://sonarcloud.io  -Dsonar.organization=openapi-tools -Dsonar.login=${SONARQUBE_TOKEN}"

cache:
  directories:
    - $HOME/.m2

